mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns=[
	path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name = 'question_detail'),
	path('questions/<int:pk>/result/', views.QuestionResultView.as_view(), name='question_result'),
	path('questions/<int:question_id>/vote/', views.question_vote, name='question_vote'),
	path('questions/', views.IndexView.as_view(), name="question_index"),


#	path('questions/', views.question_index, name="question_index"),
#	path('questions/<int:question_id>', views.question_detail, name='question_detail'),
#	path('questions/<int:question_id>/result', views.question_result, name='question_result'),
]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
	content = models.CharField(max_length = 128)
	pub_time = models.DateTimeField('date published')

	def __str__(self):
		return self.content

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	content = models.CharField(max_length = 256)
	vote = models.IntegerField(default = 0)

	def __str__(self):
		return self.content

polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


def question_index(request):

	host = request.get_host()

	latest_questions = Question.objects.order_by('pub_time')[:5]
	#view = loader.get_template('polls/index.html')
	context = {
		'latest_questions': latest_questions,
		'str': host,
	}
	return render(request, 'polls/index.html', context)
	#return HttpResponse(view.render(context, request));


def question_detail(request, question_id):
	question = get_object_or_404(Question, id = question_id)
	return render(request, 'polls/question_detail.html', {'question': question})


def question_result(request, question_id):
	question = get_object_or_404(Question, id = question_id)
	return render(request, 'polls/question_result.html', {'question': question})



class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_questions'
	
	def get_queryset(self):
		return Question.objects.order_by('pub_time')[:5]


class QuestionDetailView(generic.DetailView):
	model = Question
#	template_name = 'polls/question_detail.html'


class QuestionResultView(generic.DetailView):
	model = Question
	template_name = 'polls/question_result.html'


def question_vote(request, question_id):
	question = get_object_or_404(Question, id = question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, "polls/question_detail.html",{
			'question': question,
			'error_message': 'Did not select any one.'
		})
	selected_choice.vote += 1
	selected_choice.save()
	return HttpResponseRedirect(reverse('polls:question_result', args=(question_id,)))

polls/templates/polls/index.html
{% load static %}

<html>

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}">
</head>

<body>

{% if str %}
	{{str}}
{% endif %}

{% if latest_questions %}

<ul>
	{% for q in latest_questions %}
	<li><a href="{% url 'polls:question_detail' q.id %}">{{q.content}}</a></li>
	{% endfor %}
</ul>

{% else %}

<p>No questions are available.</p>

{% endif %}
</body>

</html>

polls/templates/polls/question_detail.html
{{question.content}}
{% if error_message %}
	{{error_message}}
{% endif %}

<form action="{% url 'polls:question_vote' question.id %}" method="post">
{%csrf_token%}
{% for c in question.choice_set.all %}
	<input type="radio" name="choice" id="choice_{{forloop.counter}}" value="{{c.id}}">
	<label for="choice_{{forloop.counter}}">{{c.content}}</label><br>
{% endfor %}
<input type=submit value="Vote">
</form>

polls/templates/polls/question_result.html
{{question.content}}

<ul>
{% for c in question.choice_set.all %}

<li>{{c.content}} -- {{c.vote}} vote{{c.vote|pluralize}}</li>
	
{% endfor %}
</ul>